sudo: false

language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
    - asciidoc
    - jpegoptim
    - libfreetype6-dev
    - libjpeg-progs
    - libjpeg8-dev
    - liblcms2-dev
    - libpcre3-dev
    - libtiff5-dev
    - libwebp-dev
    - libxml2-dev
    - libxslt1-dev
    - nodejs
    - optipng
    - python-tk
    - tcl8.5-dev
    - tk8.5-dev
    - zlib1g-dev

# Cache pip requirements for faster builds
cache:
  directories:
    - $HOME/.cache/pip

install:
  # JS dependencies
  - npm install sass@1.26.3 requirejs@2.3.6 stylus@0.54.7 uglify-js@3.8.0 less@3.10.3

  # Python test requirements
  - pip install tox

# Run each tox environment separately
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=py38
  - TOX_ENV=pep8
  - TOX_ENV=docs

before_script:
  - export PATH=$(pwd)/node_modules/.bin:$PATH
  - export PYTHONPATH=$PYTHONPATH:/usr/share/asciidoc/

script:
  - tox -e $TOX_ENV

